export const IMAGE_GUIDELINES = {
  product: {
    width: 1200,
    height: 1200,
    ratio: "1:1",
    fit: "contain",
    usage: "نمایش کامل محصول در دسکتاپ و موبایل؛ اطراف سوژه کمی فضای خالی بگذارید.",
    format: "WebP یا AVIF (در صورت نیاز PNG/JPEG)",
  },
  productRetail: { width: 1200, height: 1200, ratio: "1:1", fit: "contain", usage: "تصویر اصلی و گالری فروش تکی؛ محصول را وسط قاب قرار دهید.", format: "WebP یا AVIF" },
  productWholesale: { width: 1200, height: 1200, ratio: "1:1", fit: "contain", usage: "بسته، کارتن یا چیدمان عمده را کامل و واضح نشان دهید.", format: "WebP یا AVIF" },
  category: { width: 1000, height: 1000, ratio: "1:1", fit: "cover", usage: "تصویر دسته‌بندی؛ سوژه در مرکز امن قاب باشد.", format: "WebP یا AVIF" },
  hero: {
    width: 1600,
    height: 700,
    ratio: "16:7",
    fit: "cover",
    usage: "در قاب ۵:۴ نمایش داده و لبه‌ها ممکن است اندکی برش بخورند؛ سوژه را وسط نگه دارید.",
    format: "WebP یا AVIF",
  },
  heroMobile: { width: 1080, height: 1350, ratio: "4:5", fit: "cover", usage: "نسخه موبایل هیرو؛ متن را داخل تصویر قرار ندهید.", format: "WebP یا AVIF" },
  banner: {
    width: 1600,
    height: 500,
    ratio: "16:5",
    fit: "cover",
    usage: "در موبایل و دسکتاپ با برش کنترل‌شده نمایش داده می‌شود؛ متن را داخل خود تصویر نگذارید.",
    format: "WebP یا AVIF",
  },
  mediumBanner: { width: 1200, height: 600, ratio: "2:1", fit: "cover", usage: "برای کارت‌های تبلیغاتی متوسط؛ سوژه را از محل پنل متن دور نگه دارید.", format: "WebP یا AVIF" },
  squarePromo: { width: 1080, height: 1080, ratio: "1:1", fit: "cover", usage: "برای تبلیغ مربعی و کارت تصویری.", format: "WebP یا AVIF" },
  blogCover: {
    width: 1600,
    height: 900,
    ratio: "16:9",
    fit: "cover",
    usage: "کاور مقاله در فهرست و صفحه مطلب؛ سوژه اصلی را در مرکز امن تصویر قرار دهید.",
    format: "WebP، AVIF یا JPEG",
  },
  blogInline: {
    width: 1400,
    height: 933,
    ratio: "3:2",
    fit: "contain",
    usage: "داخل متن با عرض کامل و بدون کشیدگی نمایش داده می‌شود.",
    format: "WebP، AVIF، PNG یا JPEG",
  },
} as const;

export type ImageGuidelineKey = keyof typeof IMAGE_GUIDELINES;
